[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
gas_reports = ["*"]
optimizer = true
optimizer_runs = 200

# Network configurations
[rpc_endpoints]
local = "http://127.0.0.1:8545"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
unichain = "https://130.rpc.thirdweb.com"
unichain_sepolia = "https://sepolia.unichain.org"

# Etherscan configuration for verification
[etherscan]
unichain = { key = "${ETHERSCAN_API_KEY}", chain = 130, url = "https://unichain.blockscout.com/api" }
unichain_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 1301, url = "https://unichain-sepolia.blockscout.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
